# fly.toml app configuration file generated for apibuble on 2023-07-25T18:26:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apibuble"
primary_region = "mad"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
